routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\IndicadorController;
use App\Http\Controllers\TendenciaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('indicadors', IndicadorController::class);
Route::resource('tendencias', TendenciaController::class);

app/Models/Indicador.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Indicador extends Model
{
    use HasFactory;

    protected $fillable = [
        'nombreIndicador', 'codigoIndicador', 'unidadMedidaIndicador', 'valorIndicador', 'fechaIndicador'
    ];
}

app/Http/Controllers/IndicadorController.php
<?php

namespace App\Http\Controllers;

use App\Models\Indicador;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Brian2694\Toastr\Facades\Toastr;



class IndicadorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $indicadores = Indicador::all();
        return view('indicadors.index')->with('indicadores', $indicadores);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('indicadors.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'nombreIndicador' => 'required|string|max:255',
            'codigoIndicador' => 'required|string|max:255',
            'unidadMedidaIndicador' => 'required|string|max:255',
            'valorIndicador' => 'required|numeric|max:2147483647',
            'fechaIndicador' => 'required|string|max:255',
        ], [
            'nombreIndicador.required' => 'Este campo es obligatorio.',
            'nombreIndicador.string' => 'Debes ingresar solo letras.',
            'nombreIndicador.max' => 'Solo se permiten 255 caracteres.',
            'codigoIndicador.required' => 'Este campo es obligatorio.',
            'codigoIndicador.string' => 'Debes ingresar solo letras.',
            'codigoIndicador.max' => 'Solo se permiten 255 caracteres.',
            'unidadMedidaIndicador.required' => 'Este campo es obligatorio.',
            'unidadMedidaIndicador.string' => 'Debes ingresar solo letras.',
            'unidadMedidaIndicador.max' => 'Solo se permiten 255 caracteres.',
            'valorIndicador.required' => 'Este campo es obligatorio.',
            'valorIndicador.integer' => 'Debes ingresar solo números.',
            'valorIndicador.max' => 'Solo se permite menor a 2147483647.',
            'fechaIndicador.required' => 'Este campo es obligatorio.',
            'fechaIndicador.string' => 'Debes ingresar solo letras.',
            'fechaIndicador.max' => 'Solo se permiten 255 caracteres.',
        ]);

        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput();
        }

        try {
            Indicador::create([
                'nombreIndicador' => $request->nombreIndicador,
                'codigoIndicador' => $request->codigoIndicador,
                'unidadMedidaIndicador' => $request->unidadMedidaIndicador,
                'valorIndicador' => $request->valorIndicador,
                'fechaIndicador' => $request->fechaIndicador,
            ]);

            Toastr::success('Indicador creado correctamente');
            return redirect('indicadors');
        } catch (\Throwable $e) {
            report($e);
            dd($e);
            return false;
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Indicador  $indicador
     * @return \Illuminate\Http\Response
     */
    public function show(Indicador $indicador)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Indicador  $indicador
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $indicador = Indicador::find($id);
        return view('indicadors.edit')->with('indicador', $indicador);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Indicador  $indicador
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'nombreIndicador' => 'required|string|max:255',
            'codigoIndicador' => 'required|string|max:255',
            'unidadMedidaIndicador' => 'required|string|max:255',
            'valorIndicador' => 'required|numeric|max:2147483647',
            'fechaIndicador' => 'required|string|max:255',
        ], [
            'nombreIndicador.required' => 'Este campo es obligatorio.',
            'nombreIndicador.string' => 'Debes ingresar solo letras.',
            'nombreIndicador.max' => 'Solo se permiten 255 caracteres.',
            'codigoIndicador.required' => 'Este campo es obligatorio.',
            'codigoIndicador.string' => 'Debes ingresar solo letras.',
            'codigoIndicador.max' => 'Solo se permiten 255 caracteres.',
            'unidadMedidaIndicador.required' => 'Este campo es obligatorio.',
            'unidadMedidaIndicador.string' => 'Debes ingresar solo letras.',
            'unidadMedidaIndicador.max' => 'Solo se permiten 255 caracteres.',
            'valorIndicador.required' => 'Este campo es obligatorio.',
            'valorIndicador.integer' => 'Debes ingresar solo números.',
            'valorIndicador.max' => 'Solo se permite menor a 2147483647.',
            'fechaIndicador.required' => 'Este campo es obligatorio.',
            'fechaIndicador.string' => 'Debes ingresar solo letras.',
            'fechaIndicador.max' => 'Solo se permiten 255 caracteres.',
        ]);

        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput();
        }

        try {
            Indicador::where('id', $id)->firstOrFail()->update([
                'nombreIndicador' => $request->nombreIndicador,
                'codigoIndicador' => $request->codigoIndicador,
                'unidadMedidaIndicador' => $request->unidadMedidaIndicador,
                'valorIndicador' => $request->valorIndicador,
                'fechaIndicador' => $request->fechaIndicador,
            ]);

            Toastr::success('Indicador modificado correctamente');
            return redirect('indicadors');
        } catch (\Throwable $e) {
            report($e);
            dd($e);
            return false;
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Indicador  $indicador
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            Indicador::find($id)->delete();
            Toastr::success('Indicador eliminado correctamente');
            return redirect('indicadors');
        } catch (\Throwable $e) {
            report($e);
            dd($e);
            return false;
        }
    }
}

resources/views/indicadors/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container mt-3">
    <h1>Agregar indicador</h1>
    <hr>
    <div class="row">
        <div class="col-12">
            <a class="btn btn-secondary" href="{{ url()->previous() }}" role="button">Volver</a>
        </div>
    </div>
    <hr>
    <form action="{{ route('indicadors.store') }}" method="POST">
        @csrf
        <div class="card-body">
            <div class="row">
                <div class="form-group col-md-6">
                    <label for="InputNombreIndicador">Nombre</label>
                    <input type="text" class="form-control @error('nombreIndicador') is-invalid @enderror" name="nombreIndicador" value="{{ old('nombreIndicador') }}" autocomplete="off">
                    @error('nombreIndicador')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
                <div class="form-group col-md-6">
                    <label for="InputCodigoIndicador">Código</label>
                    <input type="text" class="form-control @error('codigoIndicador') is-invalid @enderror" name="codigoIndicador" value="{{ old('codigoIndicador') }}" autocomplete="off">
                    @error('codigoIndicador')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
                <div class="form-group col-md-6">
                    <label for="InputUnidadMedidaIndicador">Unidad de medida</label>
                    <input type="text" class="form-control @error('unidadMedidaIndicador') is-invalid @enderror" name="unidadMedidaIndicador" value="{{ old('unidadMedidaIndicador') }}" autocomplete="off">
                    @error('unidadMedidaIndicador')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
                <div class="form-group col-md-6">
                    <label for="InputValorIndicador">Valor</label>
                    <input type="text" class="form-control @error('valorIndicador') is-invalid @enderror" name="valorIndicador" value="{{ old('valorIndicador') }}" autocomplete="off">
                    @error('valorIndicador')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
                <div class="form-group col-md-6">
                    <label for="InputFechaIndicador">Fecha</label>
                    <input type="text" class="form-control @error('fechaIndicador') is-invalid @enderror" name="fechaIndicador" value="{{ old('fechaIndicador') }}" autocomplete="off" placeholder="2000/10/01">
                    @error('fechaIndicador')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
            </div>
            <br>
            <button type="submit" class="btn btn-primary">Guardar</button>
        </div>
    </form>
</div>

</div>
@endsection

resources/views/indicadors/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container mt-3">
    <h1>Editar indicador</h1>
    <hr>
    <div class="row">
        <div class="col-12">
            <a class="btn btn-secondary" href="{{ url()->previous() }}" role="button">Volver</a>
        </div>
    </div>
    <hr>
    <form action="{{ route('indicadors.update', $indicador->id) }}" method="POST">
        @csrf
        @method('put')
        <div class="card-body">
            <div class="row">
                <div class="form-group col-md-6">
                    <label for="InputNombreIndicador">Nombre</label>
                    <input type="text" class="form-control @error('nombreIndicador') is-invalid @enderror" name="nombreIndicador" value="{{ $indicador->nombreIndicador }}" autocomplete="off">
                    @error('nombreIndicador')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
                <div class="form-group col-md-6">
                    <label for="InputCodigoIndicador">Código</label>
                    <input type="text" class="form-control @error('codigoIndicador') is-invalid @enderror" name="codigoIndicador" value="{{ $indicador->codigoIndicador }}" autocomplete="off">
                    @error('codigoIndicador')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
                <div class="form-group col-md-6">
                    <label for="InputUnidadMedidaIndicador">Unidad de medida</label>
                    <input type="text" class="form-control @error('unidadMedidaIndicador') is-invalid @enderror" name="unidadMedidaIndicador" value="{{ $indicador->unidadMedidaIndicador }}" autocomplete="off">
                    @error('unidadMedidaIndicador')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
                <div class="form-group col-md-6">
                    <label for="InputValorIndicador">Valor</label>
                    <input type="text" class="form-control @error('valorIndicador') is-invalid @enderror" name="valorIndicador" value="{{ $indicador->valorIndicador }}" autocomplete="off">
                    @error('valorIndicador')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
                <div class="form-group col-md-6">
                    <label for="InputFechaIndicador">Fecha</label>
                    <input type="text" class="form-control @error('fechaIndicador') is-invalid @enderror" name="fechaIndicador" value="{{ $indicador->fechaIndicador }}" autocomplete="off" placeholder="01/01/2000">
                    @error('fechaIndicador')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
            </div>
            <br>
            <button type="submit" class="btn btn-primary">Guardar</button>
            <hr>
            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">Eliminar</button>

        </div>
    </form>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Eliminar ({{ $indicador->nombreIndicador }})</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    ¿Estás seguro de eliminar el indicador?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <form action="{{ route('indicadors.destroy',$indicador->id) }}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger">Eliminar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/indicadors/index.blade.php
@extends('layouts.app')

@push('head')
<!-- datatables -->
<link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/dataTables.bootstrap4.min.css">
@endpush

@section('content')
<div class="container mt-3">
    <h1>Indicadores</h1>
    <hr>
    <div class="row">
        <div class="col-6">
            <a class="btn btn-secondary" href="/" role="button">Volver</a>
        </div>
        <div class="col-6">
            <a class="btn btn-primary float-right" href="{{ route('indicadors.create') }}" role="button">Agregar</a>
        </div>
    </div>
    <hr>
    <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Código</th>
                <th>Unidad Med.</th>
                <th>Valor</th>
                <th>Fecha</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($indicadores as $indicador)
            <tr>
                <th scope="row"><a href="{{ route('indicadors.edit',$indicador->id) }}">{{ $indicador->id }}</a></th>
                <td>{{ $indicador->nombreIndicador }}</td>
                <td>{{ $indicador->codigoIndicador }}</td>
                <td>{{ $indicador->unidadMedidaIndicador }}</td>
                <td>{{ $indicador->valorIndicador }}</td>
                <td>{{ $indicador->fechaIndicador }}</td>
            </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Código</th>
                <th>Unidad Med.</th>
                <th>Valor</th>
                <th>Fecha</th>
            </tr>
        </tfoot>
    </table>
</div>
@endsection

@push('scripts')
<script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap4.min.js"></script>

<script>
    $(function() {
        $('#example').DataTable({
            order: [
                [0, 'asc']
            ],
            language: {
                "decimal": "",
                "emptyTable": "No hay información",
                "info": "Mostrando _START_ a _END_ de _TOTAL_ registros",
                "infoEmpty": "Mostrando 0 to 0 of 0 registros",
                "infoFiltered": "(Filtrado de _MAX_ total registros)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Mostrar _MENU_ registros",
                "loadingRecords": "Cargando...",
                "processing": "Procesando...",
                "search": "Buscar:",
                "zeroRecords": "Sin resultados encontrados",
                "paginate": {
                    "first": "Primero",
                    "last": "Ultimo",
                    "next": "Siguiente",
                    "previous": "Anterior"
                }
            },
            "paging": true,
            "lengthChange": false,
            "searching": true,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "responsive": true,

        });
    });
</script>



@endpush