routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\IndicadorController;
use App\Http\Controllers\TendenciaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('indicadors', IndicadorController::class);
Route::resource('tendencias', TendenciaController::class);

app/Http/Controllers/TendenciaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Models\Indicador;

class TendenciaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $codigos = DB::table("indicadors")
        ->select("codigoIndicador")
        ->groupBy("codigoIndicador")
        ->get();
        return view('tendencias.index')->with('codigos', $codigos);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $valores = DB::table("indicadors")
        ->select("valorIndicador", "fechaIndicador")
        ->where("codigoIndicador", "=", $request->codigoIndicador)
        ->whereBetween('fechaIndicador', [$request->fechaDesde, $request->fechaHasta])
        ->get();

        $arreglo = [];

        foreach ($valores as $valor) {

            $arreglo[] = ['y' => $valor->fechaIndicador, 'valor' => $valor->valorIndicador]; 
        }

        return view('tendencias.graphic')->with([
            'valores' => json_encode($arreglo),
            'codigo' => $request->codigoIndicador
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/tendencias/graphic.blade.php
@extends('layouts.app')

@push('head')

@endpush

@section('content')
<div class="container mt-3">
    <h1>Tendencias</h1>
    <hr>
    <a class="btn btn-secondary" href="{{ url()->previous() }}" role="button">Volver</a>
    <hr>
    <div id='graphic'></div>
</div>
@endsection

@push('scripts')
<script src="https://code.highcharts.com/highcharts.js"></script>

<script>
    var data = JSON.parse('<?php echo $valores; ?>');
    const chart = Highcharts.chart('graphic', {
        title: {
            text: '{{ $codigo }}'
        },
        xAxis: {
            type: 'datetime',
            categories: data.map(row => row.y)
        },
        yAxis: {
            title: {
                text: 'Valor'
            }
        },
        series: [{
            name: 'Valor',
            data: data.map(row => Number(row.valor)),
        }]
    });
</script>



@endpush

resources/views/tendencias/index.blade.php
@extends('layouts.app')

@push('head')

@endpush

@section('content')
<div class="container mt-3">
    <h1>Tendencias</h1>
    <hr>
    <a class="btn btn-secondary" href="/" role="button">Volver</a>
    <hr>
    <form action="{{ route('tendencias.store') }}" method="POST">
        @csrf
        <div class="card-body">
            <div class="row">
                <div class="form-group col-md-6">
                    <label for="InputCodigoIndicador">Código indicador</label>
                    <select class="custom-select form-control" id="codigoIndicador" name="codigoIndicador">
                        @foreach($codigos as $codigo)
                        <option value="{{ $codigo->codigoIndicador }}"> {{ $codigo->codigoIndicador }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group col-md-3">
                    <label for="InputFechaDesde">Fecha desde</label>
                    <input type="text" class="form-control @error('fechaDesde') is-invalid @enderror" name="fechaDesde" value="{{ old('fechaDesde') }}" autocomplete="off" placeholder="2000/01/01">
                    @error('fechaDesde')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
                <div class="form-group col-md-3">
                    <label for="InputFechaDesde">Fecha hasta</label>
                    <input type="text" class="form-control @error('fechaHasta') is-invalid @enderror" name="fechaHasta" value="{{ old('fechaHasta') }}" autocomplete="off" placeholder="2000/12/31">
                    @error('fechaHasta')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
            </div>
            <br>
            <button type="submit" class="btn btn-primary">Generar grafico</button>
        </div>
    </form>
</div>
@endsection